# Class Project

## Top Five Career on the year 1999

In [7]:
import pandas as pd
import numpy as np

fn = "../input/wikipedia_edits.csv.zip"
df = pd.read_csv(fn)

In [8]:
df

,title,parentid,revid,timestamp,user,userid,size,recipient,year,rank,country,career,tied
0,50_Cent,858765697,858858564,2018-09-10T02:52:25Z,ProspectIV,33893830.0,132452,50 Cent,2006,8,United States,Musician,0
1,50_Cent,858673799,858765697,2018-09-09T13:11:00Z,ProspectIV,33893830.0,132476,50 Cent,2006,8,United States,Musician,0
2,50_Cent,858673121,858673799,2018-09-08T21:46:42Z,ProspectIV,33893830.0,132444,50 Cent,2006,8,United States,Musician,0
3,50_Cent,858673016,858673121,2018-09-08T21:39:37Z,ProspectIV,33893830.0,132345,50 Cent,2006,8,United States,Musician,0
4,50_Cent,858469414,858673016,2018-09-08T21:38:24Z,ProspectIV,33893830.0,132345,50 Cent,2006,8,United States,Musician,0
5,50_Cent,858438339,858469414,2018-09-07T12:09:10Z,ProspectIV,33893830.0,132324,50 Cent,2006,8,United States,Musician,0
6,50_Cent,858406633,858438339,2018-09-07T05:30:10Z,Daleded,34183550.0,132314,50 Cent,2006,8,United States,Musician,0
7,50_Cent,857486883,858406633,2018-09-06T23:35:47Z,Daleded,34183550.0,132310,50 Cent,2006,8,United States,Musician,0
8,50_Cent,857286743,857486883,2018-09-01T00:12:33Z,KingArti,4614961.0,132268,50 Cent,2006,8,United States,Musician,0
9,50_Cent,857154218,857286743,2018-08-30T19:17:24Z,Callan992,29868247.0,132275,50 Cent,2006,8,United States,Musician,0
10,50_Cent,857127041,857154218,2018-08-29T22:26:20Z,Banan14kab,10157226.0,132282,50 Cent,2006,8,United States,Musician,0
11,50_Cent,856739345,857127041,2018-08-29T18:53:19Z,InternetArchiveBot,27015025.0,132276,50 Cent,2006,8,United States,Musician,0
12,50_Cent,855717684,856739345,2018-08-27T07:12:30Z,Winston Covington,33764833.0,132081,50 Cent,2006,8,United States,Musician,0
13,50_Cent,855717202,855717684,2018-08-20T10:32:59Z,Takutau,5531412.0,132062,50 Cent,2006,8,United States,Musician,0
14,50_Cent,854344908,855717202,2018-08-20T10:27:46Z,Takutau,5531412.0,132041,50 Cent,2006,8,United States,Musician,0
15,50_Cent,854251301,854344908,2018-08-10T17:04:46Z,Ss112,1286970.0,132040,50 Cent,2006,8,United States,Musician,0
16,50_Cent,854064602,854251301,2018-08-10T00:22:18Z,Tydice,34288515.0,132030,50 Cent,2006,8,United States,Musician,0
17,50_Cent,853071273,854064602,2018-08-08T18:26:36Z,JFG,168812.0,132065,50 Cent,2006,8,United States,Musician,0
18,50_Cent,852882152,853071273,2018-08-02T07:17:09Z,InternetArchiveBot,27015025.0,132051,50 Cent,2006,8,United States,Musician,0
19,50_Cent,852882062,852882152,2018-08-01T00:41:54Z,Bryantriplex,25571107.0,130966,50 Cent,2006,8,United States,Musician,0
20,50_Cent,851987209,852882062,2018-08-01T00:41:07Z,Bryantriplex,25571107.0,130965,50 Cent,2006,8,United States,Musician,0
21,50_Cent,851571353,851987209,2018-07-25T21:25:47Z,GreenC bot,27823944.0,130948,50 Cent,2006,8,United States,Musician,0
22,50_Cent,850343064,851571353,2018-07-23T05:58:46Z,InternetArchiveBot,27015025.0,130948,50 Cent,2006,8,United States,Musician,0
23,50_Cent,850311747,850343064,2018-07-15T08:17:36Z,Robvanvee,10236113.0,130460,50 Cent,2006,8,United States,Musician,0
24,50_Cent,849940120,850311747,2018-07-15T02:16:32Z,MapleTreeXZ,27394319.0,130525,50 Cent,2006,8,United States,Musician,0
25,50_Cent,849877731,849940120,2018-07-12T13:03:31Z,Namiba,1008048.0,130460,50 Cent,2006,8,United States,Musician,0
26,50_Cent,849802309,849877731,2018-07-12T00:45:40Z,Bildeberg,33867454.0,130545,50 Cent,2006,8,United States,Musician,0
27,50_Cent,849301761,849802309,2018-07-11T12:53:59Z,Captain Lloyd Banks,34128532.0,130939,50 Cent,2006,8,United States,Musician,0
28,50_Cent,849056535,849301761,2018-07-08T01:36:43Z,Captain Lloyd Banks,34128532.0,130904,50 Cent,2006,8,United States,Musician,0
29,50_Cent,849028566,849056535,2018-07-06T06:12:02Z,Winston Covington,33764833.0,130850,50 Cent,2006,8,United States,Musician,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
789313,U2,1351373,1541010,2003-08-27T06:25:14Z,Zippy,3436.0,10876,U2,2011,4,Republic of Ireland,Musicians,0
789314,U2,1171331,1351373,2003-07-20T09:58:54Z,GRAHAMUK,10999.0,10876,U2,2011,4,Republic of Ireland,Musicians,0
789315,U2,1029121,1171331,2003-06-12T23:53:58Z,66.185.84.80,0.0,10877,U2,2011,4,Republic of Ireland,Musicians,0
789316,U2,961579,1029121,2003-05-25T19:09:40Z,194.109.220.178,0.0,10868,U2,2011,4,Republic of Ireland,Musicians,0
789317,U2,961549,961579,2003-05-25T19:05:51Z,194.109.220.178,0.0,10865,U2,2011,4,Republic of Ireland,Musicians,0
789318,U2,935283,961549,2003-05-18T18:43:42Z,Yngwin,11118.0,10836,U2,2011,4,Republic of Ireland,Musicians,0
789319,U2,784815,935283,2003-03-29T05:51:05Z,Michael,8911.0,10837,U2,2011,4,Republic of Ireland,Musicians,0
789320,U2,781898,784815,2003-03-28T05:07:46Z,144.92.164.197,0.0,10833,U2,2011,4,Republic of Ireland,Musicians,0
789321,U2,768375,781898,2003-03-23T00:08:21Z,Iain,8943.0,10825,U2,2011,4,Republic of Ireland,Musicians,0
789322,U2,713164,768375,2003-03-02T00:13:38Z,Enchanter,1104.0,10628,U2,2011,4,Republic of Ireland,Musicians,0
789323,U2,713145,713164,2003-03-02T00:06:16Z,Arwel Parry,7891.0,10629,U2,2011,4,Republic of Ireland,Musicians,0
789324,U2,634691,713145,2003-02-01T03:02:07Z,67.122.115.150,0.0,10629,U2,2011,4,Republic of Ireland,Musicians,0
789325,U2,580450,634691,2003-01-12T07:23:50Z,AxelBoldt,2.0,10583,U2,2011,4,Republic of Ireland,Musicians,0
789326,U2,570794,580450,2003-01-08T07:42:10Z,216.229.90.232,0.0,10583,U2,2011,4,Republic of Ireland,Musicians,0
789327,U2,566657,570794,2003-01-07T00:45:24Z,Islandboy99,6710.0,10583,U2,2011,4,Republic of Ireland,Musicians,0
789328,U2,566168,566657,2003-01-06T22:16:23Z,Jazz77,4329.0,10524,U2,2011,4,Republic of Ireland,Musicians,0
789329,U2,566136,566168,2003-01-06T22:05:30Z,Jazz77,4329.0,10526,U2,2011,4,Republic of Ireland,Musicians,0
789330,U2,566135,566136,2003-01-06T22:04:10Z,216.229.90.232,0.0,10526,U2,2011,4,Republic of Ireland,Musicians,0
789331,U2,565582,566135,2003-01-06T17:41:12Z,Islandboy99,6710.0,1005,U2,2011,4,Republic of Ireland,Musicians,0
789332,U2,490087,565582,2002-12-13T17:57:38Z,213.224.83.150,0.0,863,U2,2011,4,Republic of Ireland,Musicians,0
789333,U2,381851,490087,2002-10-24T13:02:04Z,Nknight,3898.0,845,U2,2011,4,Republic of Ireland,Musicians,0
789334,U2,376232,381851,2002-10-22T06:44:51Z,Jazz77,4329.0,845,U2,2011,4,Republic of Ireland,Musicians,0
789335,U2,347214,376232,2002-10-09T22:00:02Z,Gareth Owen,151.0,841,U2,2011,4,Republic of Ireland,Musicians,0
789336,U2,336756,347214,2002-10-05T04:55:22Z,216.229.90.232,0.0,843,U2,2011,4,Republic of Ireland,Musicians,0
789337,U2,74600,336756,2002-05-21T11:42:23Z,JeLuF,733.0,307,U2,2011,4,Republic of Ireland,Musicians,0
789338,U2,383222001,74600,2002-02-25T15:43:11Z,Conversion script,0.0,406,U2,2011,4,Republic of Ireland,Musicians,0
789339,U2,383221849,383222001,2001-12-19T22:47:40Z,144.132.75.xxx,0.0,402,U2,2011,4,Republic of Ireland,Musicians,0
789340,U2,292008,292009,2001-12-12T08:28:48Z,202.161.127.xxx,0.0,654,U2,2011,4,Republic of Ireland,Musicians,0
789341,U2,292007,292008,2001-12-03T17:45:09Z,193.133.134.xxx,0.0,409,U2,2011,4,Republic of Ireland,Musicians,0
789342,U2,0,292007,2001-08-08T12:04:31Z,Rrees,32609845.0,395,U2,2011,4,Republic of Ireland,Musicians,0

In [12]:
df.head()

,title,parentid,revid,timestamp,user,userid,size,recipient,year,rank,country,career,tied
0,50_Cent,858765697,858858564,2018-09-10T02:52:25Z,ProspectIV,33893830.0,132452,50 Cent,2006,8,United States,Musician,0
1,50_Cent,858673799,858765697,2018-09-09T13:11:00Z,ProspectIV,33893830.0,132476,50 Cent,2006,8,United States,Musician,0
2,50_Cent,858673121,858673799,2018-09-08T21:46:42Z,ProspectIV,33893830.0,132444,50 Cent,2006,8,United States,Musician,0
3,50_Cent,858673016,858673121,2018-09-08T21:39:37Z,ProspectIV,33893830.0,132345,50 Cent,2006,8,United States,Musician,0
4,50_Cent,858469414,858673016,2018-09-08T21:38:24Z,ProspectIV,33893830.0,132345,50 Cent,2006,8,United States,Musician,0

In [19]:
df_years = pd.DataFrame(df.groupby("year"))
df_years

NameError: name 'year' is not defined